version: 2
updates:
  - package-ecosystem: github-actions
    schedule:
      interval: daily
    directory: /
    target-branch: master
    commit-message:
      prefix: chore
      include: scope
    assignees:
      - pascaliske
    labels:
      - dependencies
  - package-ecosystem: npm
    schedule:
      interval: daily
    directory: /
    target-branch: master
    versioning-strategy: increase
    commit-message:
      prefix: chore
      include: scope
    assignees:
      - pascaliske
    labels:
      - dependencies
    ignore:
      - dependency-name: '@angular/*'
        update-types:
          - version-update:semver-major
      - dependency-name: '@nguniversal/*'
        update-types:
          - version-update:semver-major
