language: node_js
node_js:
  - '12'
  - '11'
before_install: yarn global add greenkeeper-lockfile@1
install:
  - yarn install
  - yarn run build
before_script: greenkeeper-lockfile-update
script:
  - yarn run lint
  - yarn run check
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: sB7Irn3sEmAnRD+DlYY5rP7vMaPSAqnLMcZ+ipFS34I8e7tNm9GraSrTxsCFPm439oc1OQLxGBx7diDnTxqsjkZdxJgNLQ+8sVStbo1Ro9cBir0nSkBvdJ8Dl2RjnObgE2iKGsVlopVIFgsrW+yjmexgyUyKPzFgUHBXiG7dixGekh9K8n19v4Pj8ANmlRfNl0ff5R5PO1kkQ+lJN4MjGmCHS12FSrTiN0+kHQSLRAOGZKRRobxOnNgWMSvnc/uj/P/r8zeI3seYJriv6HmetciqrkWGiUA4jN1OFKCEPbrBc8qi33EX8yfVfKKyklWgI0FdOoJWv+Td89P1Ktyi3yS15f5H7EP6zddax2RWgH/QLC9rZaxKt09XEB4T8vN03ErKkjekKFJdqKbIu6+h3Vtgw/OSHN1TvnAWWWZbk7rMMXfpYASwEL1Bew3xfW5T0ijFbaAsYJ4aoe9d54JoQMgQmV1i1cjp0WdpYfW3C3QP6MIDU4avYJPSKHOPLJUav9Ca5NklGEoz5yidEbBkFaVAiaNXMtkRqNaxaPUYLuAho43Uy15Qawa3asBH+F+xP3Hnmmz11MooLOGUtFtSAFPVQbk+UGJLMNIXV2cImnAyub1R8nLwHg0qU/6y9QrX/G07a8DAUJ+Mb5OGv5i2L6J+MTsV5rEsXRCC2CFJrRs=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 12
env:
  global:
    - secure: reS04c0rNAhk4x87m7OQYv1ka1233iVM2qSeobpp407iAS+kpq0/FifHOzGGdzneufWaZFuN3ZttiKK7Yynr73pC9VDAGitu1yw01mN9QecBtu4COUN2kyfZP87X0ZYrcPMrn5Wp6won+sx7QbCqic1T0ujTxbPMdeqCGomtVKvMi0aj0uB/5baJzsWe2SjKWxsuUww1T/BW6K0Ijh+zRmHKIL+qCPiqSplyJWRJ5m8OytpzjfV171cMYRkSpltlR2vUqof8UZpa+A64whcdle4GoI+b0IG+6yKCOeBOrEP3OOtw2oKZe+P2J345tGcS+nSwEwKUFa6r7sbu7lfoPB8VeyiA5DiLq2XBE76wGbIENAP1DQG/BspltFXZuRFPiFr+h3CfZWmVIUiwy7RFxPQmyAq8FP5zz1VdzCZNnXu/jegPX+xFwbG97zCvLW6ZLxAR1OAasWwBHegZQTVUKYoCdA0o2CCxV/ciTB41f7my5L5PY1i2OUEpYcy1xs4eB4S76G+2fOy6EHMag436GhkDe1yYH1ZVdl/HCUkuULBf0iy40RSG+rV0MGcjlc9h+WsmknLUtr9fJjPdJ9h+c0rG4j+g123jsT7adKJ6eu61YvM6a4/VMvqu0jCzpMOewnvw/uN9hCFdU+Z56UCsmbFALjalUuqZ89enK1MeVGw=
    - secure: km5abuftMRzJDGKN/48YrwWbM1UG3s5FGGkEKM7XoLApPmtkl3yKTbR7k+olP/QsIsSOmq9Ri2yYnDKBqu3praX6UbylNVt1XuzeJEi2GPbAf09PzjeIRcHN/xUV4AbiDsN4a65FBGII4q3LCqxoQzy/FtQuqrO0BnABl9PCX7wU5Mr7e1urIoi4LP12MZ1YpmC4rDZzBTs66O+2fV2NoBT2e2+gwDYlM0ahS1hoBKkVr7ASP397c7IxIPLutPFbPkg4C9wr3nu2b+Gs8Rh2DaJZlBLUyhRfMhkYJY8cQeekseXpEZA8rmReyLuSTm70ubYFSFYb9POVNu3zMaLu91wGuFxFyuH+ZGFUlK4bdnJ0WP3wejFCZ3a8EXDM8FW5yXJtm9ERhnJU1q2sV7MuSsftdYO/Bix6v3FPJfRIUnRGW//b9UY1W08OwFRrrc2sRyxxAjN8DHH3KCKvSBY0ox9JHg0vWj6mzugP+EjtISIobA2Zjrm7wA2tWc+u5kAtsLZeOzMSK4nAIFCbz3meY1yDNpkp73HkuqJQzSJ7rLFIXsrKxKVya1C3Pk0nxMW3ZuSgebePqSVFhbOqICFOi29tOfClYwoGt5kiK+BgRaAtVE1UXIqsHjNeX17lG7HVYut0S+Wa3ZHOXqTfA30O7BtseYmghF0Yh2VKrWT5I14=
notifications:
  slack:
    secure: pjHjQtjS1dMvan3/Xru0UryoHijpSqlxxvw2M/18AYFl2z1ltZ8lVthYQKgmF2gHK5xJ9LD/paQ9W1Mp5mpdTZLtc200OiyoT2wjNO/u+YeBAWR1AmIcola8MyE4oULf/sukfeBr/xlwQDjkisA+vvBmyg0rGcffe9BWWU97wkK/EVQxp51G/wq4DToX+Q/+pjvnOw9ACQe7P1ENdYSzVqU7PABV7U9hUhmJ8vtXF/0i3nRt8ou5ph0PuUuAAxdu2nl3wGVI5kaJ29Mr+0iAZWzSCvzfTLaJneqvWMg/DdqPTB+geu0xtmbJqA1GzgAiBV7P+hRHvXD+fa5YXA9Nf2kMTNze4RKncO8mK5xiOAbG0EYg1KrBMQcLnuHCDAqx4rqgxGKY2Z1wjHDLVfE4BgLlAODHvUthj74TT3vpwM3z/muab0BT3pThK4O5Y+7bU+LPHJNoUBw8rK/glKvlo+8peIjU/O51j8yvu9qEWhcP5epz0eie2VuoGdpbdFkQoS+8BfpC7PWg7eQQCDOK11BKWh6mgcN4Z1yQrhg3Lr4GectzUChQxcDyZe9xhb04IURo1wUnZZxg9keAbWL6CVCqoHcOXI5UyzfTl7p0FzwQRDe/kBi1WLuN4Zf3NfvK6qZLld1T/HhEXzGI3Ttk6RNCQ4ISdwcVDo0oX2newCw=
