language: node_js
node_js:
  - '13'
  - '12'
install:
  - yarn install --frozen-lockfile
script:
  - yarn run build
  - yarn run lint
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: sB7Irn3sEmAnRD+DlYY5rP7vMaPSAqnLMcZ+ipFS34I8e7tNm9GraSrTxsCFPm439oc1OQLxGBx7diDnTxqsjkZdxJgNLQ+8sVStbo1Ro9cBir0nSkBvdJ8Dl2RjnObgE2iKGsVlopVIFgsrW+yjmexgyUyKPzFgUHBXiG7dixGekh9K8n19v4Pj8ANmlRfNl0ff5R5PO1kkQ+lJN4MjGmCHS12FSrTiN0+kHQSLRAOGZKRRobxOnNgWMSvnc/uj/P/r8zeI3seYJriv6HmetciqrkWGiUA4jN1OFKCEPbrBc8qi33EX8yfVfKKyklWgI0FdOoJWv+Td89P1Ktyi3yS15f5H7EP6zddax2RWgH/QLC9rZaxKt09XEB4T8vN03ErKkjekKFJdqKbIu6+h3Vtgw/OSHN1TvnAWWWZbk7rMMXfpYASwEL1Bew3xfW5T0ijFbaAsYJ4aoe9d54JoQMgQmV1i1cjp0WdpYfW3C3QP6MIDU4avYJPSKHOPLJUav9Ca5NklGEoz5yidEbBkFaVAiaNXMtkRqNaxaPUYLuAho43Uy15Qawa3asBH+F+xP3Hnmmz11MooLOGUtFtSAFPVQbk+UGJLMNIXV2cImnAyub1R8nLwHg0qU/6y9QrX/G07a8DAUJ+Mb5OGv5i2L6J+MTsV5rEsXRCC2CFJrRs=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 13
notifications:
  slack:
    rooms:
      - secure: pjHjQtjS1dMvan3/Xru0UryoHijpSqlxxvw2M/18AYFl2z1ltZ8lVthYQKgmF2gHK5xJ9LD/paQ9W1Mp5mpdTZLtc200OiyoT2wjNO/u+YeBAWR1AmIcola8MyE4oULf/sukfeBr/xlwQDjkisA+vvBmyg0rGcffe9BWWU97wkK/EVQxp51G/wq4DToX+Q/+pjvnOw9ACQe7P1ENdYSzVqU7PABV7U9hUhmJ8vtXF/0i3nRt8ou5ph0PuUuAAxdu2nl3wGVI5kaJ29Mr+0iAZWzSCvzfTLaJneqvWMg/DdqPTB+geu0xtmbJqA1GzgAiBV7P+hRHvXD+fa5YXA9Nf2kMTNze4RKncO8mK5xiOAbG0EYg1KrBMQcLnuHCDAqx4rqgxGKY2Z1wjHDLVfE4BgLlAODHvUthj74TT3vpwM3z/muab0BT3pThK4O5Y+7bU+LPHJNoUBw8rK/glKvlo+8peIjU/O51j8yvu9qEWhcP5epz0eie2VuoGdpbdFkQoS+8BfpC7PWg7eQQCDOK11BKWh6mgcN4Z1yQrhg3Lr4GectzUChQxcDyZe9xhb04IURo1wUnZZxg9keAbWL6CVCqoHcOXI5UyzfTl7p0FzwQRDe/kBi1WLuN4Zf3NfvK6qZLld1T/HhEXzGI3Ttk6RNCQ4ISdwcVDo0oX2newCw=
    on_success: never
    on_failure: always
    on_pull_requests: false
